<?php

namespace AppBundle\Repository;

/**
 * CronjobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronjobRepository extends \Doctrine\ORM\EntityRepository
{
}
