<?php

namespace AppBundle\Repository;

/**
 * CronjobScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronjobScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
